/// Struct used by all parts of the program to note the location information
/// of the different tokens and expressions generated by the `Lexer` and the
/// `Parser` respectively.
#[derive(Debug, Clone)]
pub struct Span {
    // The name of the file.
    pub file_name: String,
    // The line where this span starts.
    pub line_start: usize,
    // The column where this span starts.
    pub column_start: usize,
    // The line where this span ends.
    pub line_end: usize,
    // The column where this span ends.
    pub column_end: usize,
}

impl Span {
    /// Creates a new `Span`.
    pub fn new(
        file_name: String,
        line_start: usize,
        column_start: usize,
        line_end: usize,
        column_end: usize,
    ) -> Self {
        Self {
            file_name,
            line_start,
            column_start,
            line_end,
            column_end,
        }
    }
}
