[package]
name = "envious"
version = "0.1.0"
authors = ["Revanth Pothukuchi <revanthpothukuchi123@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
home = "0.5.3"
envyc = { path = "../envyc" }
envious-tui = { path = "../envious-tui" }