pub mod buffer;

use smallvec::SmallVec;

use crate::source::Span;

#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    IntLiteral,

    EndOfFile,
    /// A placeholder token for any errors that
    /// occur during lexing.
    Error,
}

/// A category of source text that does not contribute
/// a token to the language grammar, e.g. whitespace
/// and comments.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriviaKind {
    Whitespace,
    Comment,
    Newline,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Trivia {
    pub(crate) kind: TriviaKind,
    pub(crate) span: Span,
}

/// An in-memory representation of a single token.
///
/// [`Token`]s are generated by the lexer and are stored
/// within the [`buffer::TokenizedBuffer`].
#[derive(Debug)]
pub struct Token {
    pub(crate) kind: TokenKind,
    pub(crate) span: Span,
    pub(crate) leading: SmallVec<[Trivia; 1]>,
    pub(crate) trailing: SmallVec<[Trivia; 1]>,
}
