/// The token module, which contains the Token struct. This struct maintains the position and the kind of the token. These are generated by the lexer.
pub mod token;

/// The token_kind module, which contains the TokenKind enum. This enum describes the various kinds of tokens that are recognized.
pub mod token_kind;
