name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting this issue! We will definitely look into it.'
        pr-message: 'Welcome! Thank you for submitting a pull request! We hope you continue to improve this project!
